## FETCHING DATA

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df_option_data=pd.read_csv('/content/hal_ki_chain.csv')

In [71]:

df_option_data.head()
requirred_data=df_option_data.iloc[:,[4,10]]
requirred_data

       LTP  STRIKE
0      740  4000.0
1        -  4100.0
2    553.9  4200.0
3   519.35  4300.0
4      412  4400.0
5      314  4500.0
6   254.35  4600.0
7   200.65  4700.0
8    155.7  4800.0
9    120.8  4900.0
10      94  5000.0
11    72.7  5100.0
12    55.9  5200.0
13      44  5300.0
14    35.4  5400.0
15      29  5500.0
16    24.3  5600.0
17   19.25  5700.0
18    15.6  5800.0
19      13  5900.0
20      12  6000.0
21     9.9  6100.0
22     7.5  6200.0
23     5.5  6400.0

In [72]:
new_data_frame=requirred_data.drop(index=[1]).reset_index(drop=True)
new_data_frame['LTP']=new_data_frame['LTP'].astype(float)
new_data_frame['STRIKE']=new_data_frame['STRIKE'].astype(str).str.replace(',','').astype(float)

new_data_frame
my_strike_list=new_data_frame.iloc[:,1]
my_strike_list

0     4000.0
1     4200.0
2     4300.0
3     4400.0
4     4500.0
5     4600.0
6     4700.0
7     4800.0
8     4900.0
9     5000.0
10    5100.0
11    5200.0
12    5300.0
13    5400.0
14    5500.0
15    5600.0
16    5700.0
17    5800.0
18    5900.0
19    6000.0
20    6100.0
21    6200.0
22    6400.0
Name: STRIKE, dtype: float64

In [73]:


my_outer_list=[]
for i in range(len(new_data_frame)):
  my_list=[]
  for j in range(len(new_data_frame)):
    my_list.append(new_data_frame.iloc[i,0]-new_data_frame.iloc[j,0])

  my_outer_list.append(my_list)

df_max_loss=pd.DataFrame(my_outer_list)

my_outer_list_spread=[]
for i in range(len(new_data_frame)):
  my_list=[]
  for j in range(len(new_data_frame)):
    my_list.append(new_data_frame.iloc[i,1]-new_data_frame.iloc[j,1])

  my_outer_list_spread.append(my_list)

df_spread=pd.DataFrame(my_outer_list_spread)

print(df_spread,df_max_loss)

        0       1       2       3       4       5       6       7       8   \
0      0.0  -200.0  -300.0  -400.0  -500.0  -600.0  -700.0  -800.0  -900.0
1    200.0     0.0  -100.0  -200.0  -300.0  -400.0  -500.0  -600.0  -700.0
2    300.0   100.0     0.0  -100.0  -200.0  -300.0  -400.0  -500.0  -600.0
3    400.0   200.0   100.0     0.0  -100.0  -200.0  -300.0  -400.0  -500.0
4    500.0   300.0   200.0   100.0     0.0  -100.0  -200.0  -300.0  -400.0
5    600.0   400.0   300.0   200.0   100.0     0.0  -100.0  -200.0  -300.0
6    700.0   500.0   400.0   300.0   200.0   100.0     0.0  -100.0  -200.0
7    800.0   600.0   500.0   400.0   300.0   200.0   100.0     0.0  -100.0
8    900.0   700.0   600.0   500.0   400.0   300.0   200.0   100.0     0.0
9   1000.0   800.0   700.0   600.0   500.0   400.0   300.0   200.0   100.0
10  1100.0   900.0   800.0   700.0   600.0   500.0   400.0   300.0   200.0
11  1200.0  1000.0   900.0   800.0   700.0   600.0   500.0   400.0   300.0
12  1300.0  1100.0  1000.0   900.0   800.0   700.0   600.0   500.0   400.0
13  1400.0  1200.0  1100.0  1000.0   900.0   800.0   700.0   600.0   500.0
14  1500.0  1300.0  1200.0  1100.0  1000.0   900.0   800.0   700.0   600.0
15  1600.0  1400.0  1300.0  1200.0  1100.0  1000.0   900.0   800.0   700.0
16  1700.0  1500.0  1400.0  1300.0  1200.0  1100.0  1000.0   900.0   800.0
17  1800.0  1600.0  1500.0  1400.0  1300.0  1200.0  1100.0  1000.0   900.0
18  1900.0  1700.0  1600.0  1500.0  1400.0  1300.0  1200.0  1100.0  1000.0
19  2000.0  1800.0  1700.0  1600.0  1500.0  1400.0  1300.0  1200.0  1100.0
20  2100.0  1900.0  1800.0  1700.0  1600.0  1500.0  1400.0  1300.0  1200.0
21  2200.0  2000.0  1900.0  1800.0  1700.0  1600.0  1500.0  1400.0  1300.0
22  2400.0  2200.0  2100.0  2000.0  1900.0  1800.0  1700.0  1600.0  1500.0

        9   ...      13      14      15      16      17      18      19  \
0  -1000.0  ... -1400.0 -1500.0 -1600.0 -1700.0 -1800.0 -1900.0 -2000.0
1   -800.0  ... -1200.0 -1300.0 -1400.0 -1500.0 -1600.0 -1700.0 -1800.0
2   -700.0  ... -1100.0 -1200.0 -1300.0 -1400.0 -1500.0 -1600.0 -1700.0
3   -600.0  ... -1000.0 -1100.0 -1200.0 -1300.0 -1400.0 -1500.0 -1600.0
4   -500.0  ...  -900.0 -1000.0 -1100.0 -1200.0 -1300.0 -1400.0 -1500.0
5   -400.0  ...  -800.0  -900.0 -1000.0 -1100.0 -1200.0 -1300.0 -1400.0
6   -300.0  ...  -700.0  -800.0  -900.0 -1000.0 -1100.0 -1200.0 -1300.0
7   -200.0  ...  -600.0  -700.0  -800.0  -900.0 -1000.0 -1100.0 -1200.0
8   -100.0  ...  -500.0  -600.0  -700.0  -800.0  -900.0 -1000.0 -1100.0
9      0.0  ...  -400.0  -500.0  -600.0  -700.0  -800.0  -900.0 -1000.0
10   100.0  ...  -300.0  -400.0  -500.0  -600.0  -700.0  -800.0  -900.0
11   200.0  ...  -200.0  -300.0  -400.0  -500.0  -600.0  -700.0  -800.0
12   300.0  ...  -100.0  -200.0  -300.0  -400.0  -500.0  -600.0  -700.0
13   400.0  ...     0.0  -100.0  -200.0  -300.0  -400.0  -500.0  -600.0
14   500.0  ...   100.0     0.0  -100.0  -200.0  -300.0  -400.0  -500.0
15   600.0  ...   200.0   100.0     0.0  -100.0  -200.0  -300.0  -400.0
16   700.0  ...   300.0   200.0   100.0     0.0  -100.0  -200.0  -300.0
17   800.0  ...   400.0   300.0   200.0   100.0     0.0  -100.0  -200.0
18   900.0  ...   500.0   400.0   300.0   200.0   100.0     0.0  -100.0
19  1000.0  ...   600.0   500.0   400.0   300.0   200.0   100.0     0.0
20  1100.0  ...   700.0   600.0   500.0   400.0   300.0   200.0   100.0
21  1200.0  ...   800.0   700.0   600.0   500.0   400.0   300.0   200.0
22  1400.0  ...  1000.0   900.0   800.0   700.0   600.0   500.0   400.0

        20      21      22
0  -2100.0 -2200.0 -2400.0
1  -1900.0 -2000.0 -2200.0
2  -1800.0 -1900.0 -2100.0
3  -1700.0 -1800.0 -2000.0
4  -1600.0 -1700.0 -1900.0
5  -1500.0 -1600.0 -1800.0
6  -1400.0 -1500.0 -1700.0
7  -1300.0 -1400.0 -1600.0
8  -1200.0 -1300.0 -1500.0
9  -1100.0 -1200.0 -1400.0
10 -1000.0 -1100.0 -1300.0
11  -900.0 -1000.0 -1200.0
12  -800.0  -900.0 -1100.0
13  -700.0  -800.0 -1000.0
14  -600.0  -700.0  -900.0
15  -500.0  -600.0  -800.0
16  -400.0  -500.0  -700.0
17  -300.0  -400.0  -600.0
18  -200.0  -300.0  -500.0
19  -100.0  -200.0  -400.0
20     0.0  -100.0  -300.0
21   100.0     0.0  -200.0
22   300.0   200.0     0.0

[23 rows x 23 columns]         0       1       2       3       4       5       6       7       8   \
0     0.00  186.10  220.65  328.00  426.00  485.65  539.35  584.30  619.20
1  -186.10    0.00   34.55  141.90  239.90  299.55  353.25  398.20  433.10
2  -220.65  -34.55    0.00  107.35  205.35  265.00  318.70  363.65  398.55
3  -328.00 -141.90 -107.35    0.00   98.00  157.65  211.35  256.30  291.20
4  -426.00 -239.90 -205.35  -98.00    0.00   59.65  113.35  158.30  193.20
5  -485.65 -299.55 -265.00 -157.65  -59.65    0.00   53.70   98.65  133.55
6  -539.35 -353.25 -318.70 -211.35 -113.35  -53.70    0.00   44.95   79.85
7  -584.30 -398.20 -363.65 -256.30 -158.30  -98.65  -44.95    0.00   34.90
8  -619.20 -433.10 -398.55 -291.20 -193.20 -133.55  -79.85  -34.90    0.00
9  -646.00 -459.90 -425.35 -318.00 -220.00 -160.35 -106.65  -61.70  -26.80
10 -667.30 -481.20 -446.65 -339.30 -241.30 -181.65 -127.95  -83.00  -48.10
11 -684.10 -498.00 -463.45 -356.10 -258.10 -198.45 -144.75  -99.80  -64.90
12 -696.00 -509.90 -475.35 -368.00 -270.00 -210.35 -156.65 -111.70  -76.80
13 -704.60 -518.50 -483.95 -376.60 -278.60 -218.95 -165.25 -120.30  -85.40
14 -711.00 -524.90 -490.35 -383.00 -285.00 -225.35 -171.65 -126.70  -91.80
15 -715.70 -529.60 -495.05 -387.70 -289.70 -230.05 -176.35 -131.40  -96.50
16 -720.75 -534.65 -500.10 -392.75 -294.75 -235.10 -181.40 -136.45 -101.55
17 -724.40 -538.30 -503.75 -396.40 -298.40 -238.75 -185.05 -140.10 -105.20
18 -727.00 -540.90 -506.35 -399.00 -301.00 -241.35 -187.65 -142.70 -107.80
19 -728.00 -541.90 -507.35 -400.00 -302.00 -242.35 -188.65 -143.70 -108.80
20 -730.10 -544.00 -509.45 -402.10 -304.10 -244.45 -190.75 -145.80 -110.90
21 -732.50 -546.40 -511.85 -404.50 -306.50 -246.85 -193.15 -148.20 -113.30
22 -734.50 -548.40 -513.85 -406.50 -308.50 -248.85 -195.15 -150.20 -115.30

        9   ...      13      14      15      16      17      18      19  \
0   646.00  ...  704.60  711.00  715.70  720.75  724.40  727.00  728.00
1   459.90  ...  518.50  524.90  529.60  534.65  538.30  540.90  541.90
2   425.35  ...  483.95  490.35  495.05  500.10  503.75  506.35  507.35
3   318.00  ...  376.60  383.00  387.70  392.75  396.40  399.00  400.00
4   220.00  ...  278.60  285.00  289.70  294.75  298.40  301.00  302.00
5   160.35  ...  218.95  225.35  230.05  235.10  238.75  241.35  242.35
6   106.65  ...  165.25  171.65  176.35  181.40  185.05  187.65  188.65
7    61.70  ...  120.30  126.70  131.40  136.45  140.10  142.70  143.70
8    26.80  ...   85.40   91.80   96.50  101.55  105.20  107.80  108.80
9     0.00  ...   58.60   65.00   69.70   74.75   78.40   81.00   82.00
10  -21.30  ...   37.30   43.70   48.40   53.45   57.10   59.70   60.70
11  -38.10  ...   20.50   26.90   31.60   36.65   40.30   42.90   43.90
12  -50.00  ...    8.60   15.00   19.70   24.75   28.40   31.00   32.00
13  -58.60  ...    0.00    6.40   11.10   16.15   19.80   22.40   23.40
14  -65.00  ...   -6.40    0.00    4.70    9.75   13.40   16.00   17.00
15  -69.70  ...  -11.10   -4.70    0.00    5.05    8.70   11.30   12.30
16  -74.75  ...  -16.15   -9.75   -5.05    0.00    3.65    6.25    7.25
17  -78.40  ...  -19.80  -13.40   -8.70   -3.65    0.00    2.60    3.60
18  -81.00  ...  -22.40  -16.00  -11.30   -6.25   -2.60    0.00    1.00
19  -82.00  ...  -23.40  -17.00  -12.30   -7.25   -3.60   -1.00    0.00
20  -84.10  ...  -25.50  -19.10  -14.40   -9.35   -5.70   -3.10   -2.10
21  -86.50  ...  -27.90  -21.50  -16.80  -11.75   -8.10   -5.50   -4.50
22  -88.50  ...  -29.90  -23.50  -18.80  -13.75  -10.10   -7.50   -6.50

        20      21      22
0   730.10  732.50  734.50
1   544.00  546.40  548.40
2   509.45  511.85  513.85
3   402.10  404.50  406.50
4   304.10  306.50  308.50
5   244.45  246.85  248.85
6   190.75  193.15  195.15
7   145.80  148.20  150.20
8   110.90  113.30  115.30
9    84.10   86.50   88.50
10   62.80   65.20   67.20
11   46.00   48.40   50.40
12   34.10   36.50   38.50
13   25.50   27.90   29.90
14   19.10   21.50   23.50
15   14.40   16.80   18.80
16    9.35   11.75   13.75
17    5.70    8.10   10.10
18    3.10    5.50    7.50
19    2.10    4.50    6.50
20    0.00    2.40    4.40
21   -2.40    0.00    2.00
22   -4.40   -2.00    0.00

[23 rows x 23 columns]

In [74]:

df_risk_reward=(-df_spread-df_max_loss)/df_max_loss
# print(df_risk_reward)
df_risk_reward=df_risk_reward.unstack().sort_values(ascending=False).dropna().drop_duplicates()
my_loss_listt=[]
my_max_profit_list=[]
for i in range(len(df_risk_reward)):
  my_loss_listt.append(df_max_loss.iloc[df_risk_reward.index[i][1],df_risk_reward.index[i][0]])
  my_max_profit_list.append(-df_spread.iloc[df_risk_reward.index[i][1],df_risk_reward.index[i][0]]-df_max_loss.iloc[df_risk_reward.index[i][1],df_risk_reward.index[i][0]])

df_risk_reward=pd.DataFrame(df_risk_reward)
df_risk_reward['loss']=my_loss_listt
df_risk_reward['profit']=my_max_profit_list

df_risk_reward=df_risk_reward[df_risk_reward['loss']>0 ]
df_risk_reward=df_risk_reward[df_risk_reward[0]>0 ]

In [75]:
strike_1=[]
strike_2=[]
for i in range(len(df_risk_reward)):
  strike_1.append(my_strike_list[df_risk_reward.index[i][0]])
  strike_2.append(my_strike_list[df_risk_reward.index[i][1]])
df_risk_reward['strike_1']=strike_1
df_risk_reward['strike_2']=strike_2
df_risk_reward.columns=['reward','loss','profit','strike_1','strike_2']
df_risk_reward.reset_index(drop=True)
df_risk_reward.index
my_strike_list

0     4000.0
1     4200.0
2     4300.0
3     4400.0
4     4500.0
5     4600.0
6     4700.0
7     4800.0
8     4900.0
9     5000.0
10    5100.0
11    5200.0
12    5300.0
13    5400.0
14    5500.0
15    5600.0
16    5700.0
17    5800.0
18    5900.0
19    6000.0
20    6100.0
21    6200.0
22    6400.0
Name: STRIKE, dtype: float64

In [76]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df_risk_reward)

https://docs.google.com/spreadsheets/d/1XigumAiIU5t6XR9jmQmwULh85LsAwdtd-MgG3PDfSJ8#gid=0